project:
  type: website
  output-dir: _site
  resources:
    - "weeks/*/released/*.pdf"

website:
  title: "Advanced Mathematical Tools for Management"
  description: "MATH 40604A, Fall 2026 at HEC Montreal"
  search:
    location: sidebar
    type: textbox
  sidebar:
    style: docked
    collapse-level: 1
    contents:
      - text: "Course information"
        href: index.qmd
      - section: "Week 1 - Modelling, sets, and algebra"
        href: weeks/w01/index.qmd
        contents:
          - weeks/w01/w01-1-preclass.qmd
          - weeks/w01/w01-2-preclass-ex.qmd
          # - weeks/w01/w01-3-lecture.qmd
          - weeks/w01/w01-4-tutorial.qmd
  page-footer:
    left: "MATH 40604A"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: outline.qmd
        text: Outline

# author: 
#   - "Fatiha Kacher"
#   - "Khaled Fouda"
date: today
date-format: "MMMM YYYY"


format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-depth: 3
    toc-title: "On this page"
    number-sections: true
    html-math-method: mathjax
    code-copy: true
    fig-align: center
  pdf:
    documentclass: scrartcl
    papersize: letter
    geometry:
      - margin=2.5cm
    toc: true
    toc-depth: 2
    number-sections: true
    colorlinks: true
    include-in-header:
      - file: tex/macros.tex

execute:
  freeze: auto
editor: source
